# Generated by Django 3.2 on 2021-05-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('english_marks', models.IntegerField()),
                ('physics_marks', models.IntegerField()),
                ('chemistry_marks', models.IntegerField()),
            ],
        ),
    ]
