# Generated by Django 3.2.3 on 2021-05-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabs',
            name='current_latitude',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='cabs',
            name='current_longitude',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
