# Generated by Django 3.2.3 on 2021-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0002_auto_20210530_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabs',
            name='current_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cabs',
            name='current_longitude',
            field=models.FloatField(),
        ),
    ]
